Flag = {
	NOTHING 	= 0x0,
	BLOCKED 	= 0x1,
	ROOM 		= 0x2,
	CORRIDOR 	= 0x4,
	PERIMETER 	= 0x10,
	ENTRANCE 	= 0x20,
	ROOM_ID 	= 0xFFC0,
	ARCH 		= 0x10000,
	DOOR 		= 0x20000,
	LOCKED 		= 0x40000,
	TRAPPED 	= 0x80000,
	SECRET 		= 0x100000,
	PORTC 		= 0x200000,
	STAIR_DN 	= 0x400000,
	STAIR_UP 	= 0x800000,
	LABEL 		= 0xFF000000,
}

local DOORSPACE = bit.bor(
	Flag.ARCH,
	Flag.DOOR,
	Flag.LOCKED,
	Flag.TRAPPED,
	Flag.SECRET,
	Flag.PORTC
)

Mask = {
	OPENSPACE 		= bit.bor(Flag.ROOM, Flag.CORRIDOR),
	DOORSPACE 		= DOORSPACE,
	ESPACE 			= bit.bor(Flag.ENTRANCE, DOORSPACE, Flag.LABEL),
	STAIRS 			= bit.bor(Flag.STAIR_DN, Flag.STAIR_UP),
	BLOCK_ROOM 		= bit.bor(Flag.BLOCKED, Flag.ROOM),
	BLOCK_CORR 		= bit.bor(Flag.BLOCKED, Flag.PERIMETER, Flag.CORRIDOR),
	BLOCK_DOOR 		= bit.bor(Flag.BLOCKED, DOORSPACE),
	ROOM_ENTRANCE 	= bit.bor(Flag.ROOM, Flag.ENTRANCE),
}
